// <auto-generated />
using FinalProjectCsharp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinalProjectCsharp.Migrations
{
    [DbContext(typeof(PatientDBContext))]
    [Migration("20241228045657_IntialCreate1")]
    partial class IntialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinalProjectCsharp.Model.Patient", b =>
                {
                    b.Property<int>("pId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("pId"));

                    b.Property<string>("appDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pDisease")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pMobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("pName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("pId");

                    b.ToTable("Patient");
                });
#pragma warning restore 612, 618
        }
    }
}
